version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_data_modeling
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data_modeling_course:/var/lib/postgresql/data
      - ./Yh_labb/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  data_modeling_course:
